"""
Django settings for openaset project.

Generated by 'django-admin startproject' using Django 1.8.18.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h5+*mo2f0n9&q1&e4%_pok=y%af_q0e4c4zpmontp8p0jwg$77'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'umum',
    'peralatanmesin',
    'gedungbangunan',
    'jalanirigasijaringan',
    'atl',

    'awayan',
    'bappeda',
    'batumandi',
    'batupiring',
    'bkd',
    'bkppd',
    'bpbd',
    'bppd',
    'dinkes',
    'disdik',
    'dishub',
    'disnakertrans',
    'distamben',
    'dko',
    'dkp',
    'dkukmp',
    'dlh',
    'dpkp',
    'dpmd',
    'dpmptsp',
    'dppkb',
    'dpppa',
    'dpupr',
    'dukcatpil',
    'halong',
    'inspektorat',
    'juai',
    'kearsipan',
    'kehutanan',
    'kesbangpol',
    'kominfo',
    'korpri',
    'lampihong',
    'paringin',
    'paringinkota',
    'paringinselatan',
    'paringintimur',
    'pariwisata',
    'perdagangan',
    'perikanan',
    'perpustakaan',
    'pertanian',
    'rsud',
    'satpolpp',
    'setda',
    'setwan',
    'sosial',
    'tebingtinggi',

    'dinkesawayan',
    'dinkesbatumandi',
    'dinkeshalong',
    'dinkesjuai',
    'dinkeskantor',
    'dinkeslampihong',
    'dinkeslokbatu',
    'dinkesparingin',
    'dinkesparinginselatan',
    'dinkespirsus',
    'dinkestebingtinggi',
    'dinkestanahhabang',
    'dinkesuren',
    'dinkesrsud',

    'disdikawayan',
    'disdikbatumandi',
    'disdikhalong',
    'disdikjuai',
    'disdikkantor',
    'disdiklampihong',
    'disdikparingin',
    'disdikparinginselatan',
    'disdiktebingtinggi',

    'disdiksmpn1awayan',
    'disdiksmpn1batumandi',
    'disdiksmpn1halong',
    'disdiksmpn1juai',
    'disdiksmpn1lampihong',
    'disdiksmpn1paringin',
    'disdiksmpn2awayan',
    'disdiksmpn2batumandi',
    'disdiksmpn2halong',
    'disdiksmpn2juai',
    'disdiksmpn2lampihong',
    'disdiksmpn2paringin',
    'disdiksmpn3awayan',
    'disdiksmpn3batumandi',
    'disdiksmpn3halong',
    'disdiksmpn3paringin',
    'disdiksmpn4awayan',
    'disdiksmpn4batumandi',
    'disdiksmpn4halong',
    'disdiksmpn4paringin',
    'disdiksmpn5halong',
    'disdiksmpn5paringin',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'openaset.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'openaset.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'latihan',
        'USER': 'latihan',
        'PASSWORD': 'latihan',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
